# This is a basic workflow to help you get started with Actions

name: Release Deploy


on:
  release:
    types:
      - created
      
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      VERSION: $(cat VERSION)
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Check shell
      run: |
        echo $0
        
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Windows build
      if: matrix.os == 'windows-latest'
      run: |
        ./pyinstaller_start.sh
        
    - name: Windows compress build
      if: matrix.os == 'windows-latest'
      run: |
        ls
        ls build
        7z a -tzip SqlDiff_win.zip build\dist\SqlDiff
      
    - name: Upload asset
      uses: softprops/action-gh-release@v1
      with:
        files: SqlDiff_win.zip
#         tag_name: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
